

CREATE TABLE APP_USERS (
    USER_ID INTEGER PRIMARY KEY,
    EMAIL VARCHAR(200) UNIQUE NOT NULL
);

CREATE SEQUENCE USER_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE;

CREATE OR REPLACE TRIGGER TRG_BEFORE_INSERT_APP_USERS
BEFORE INSERT ON APP_USERS
FOR EACH ROW
BEGIN
    SELECT USER_ID_SEQ.NEXTVAL INTO :new.USER_ID FROM DUAL;
END;
/

CREATE TABLE APP_TASKS (
    TASK_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER,
    TASK_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(255),
    STATUS VARCHAR(20) CHECK(STATUS IN ('COMPLETE','PENDING')) NOT NULL,
    DUE_DATE DATE,
    CATEGORY VARCHAR(20) CHECK(CATEGORY IN ('friends', 'family', 'personal', 'myself', 'office', 'work')),  -- Add this line for the new CATEGORY column
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES APP_USERS(USER_ID)
);


CREATE SEQUENCE TASK_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE;

CREATE OR REPLACE TRIGGER TRG_BEFORE_INSERT_APP_TASKS
BEFORE INSERT ON APP_TASKS
FOR EACH ROW
BEGIN
    SELECT TASK_ID_SEQ.NEXTVAL INTO :new.TASK_ID FROM DUAL;
END;
/

INSERT INTO APP_USERS(USER_ID, EMAIL) VALUES (USER_ID_SEQ.NEXTVAL, 'satwi@gmail.com');
INSERT INTO APP_USERS(USER_ID, EMAIL) VALUES (USER_ID_SEQ.NEXTVAL, 'usha@gmail.com');
INSERT INTO APP_USERS(USER_ID,EMAIL) VALUES (USER_ID_SEQ.NEXTVAL,'konda@gmail.com');
INSERT INTO APP_USERS(USER_ID,EMAIL) VALUES (USER_ID_SEQ.NEXTVAL,'yelaka@gmail.com');
INSERT INTO APP_USERS(USER_ID,EMAIL) VALUES (USER_ID_SEQ.NEXTVAL,'nikku@gmail.com');
INSERT INTO APP_USERS(USER_ID,EMAIL) VALUES (USER_ID_SEQ.NEXTVAL,'somu@gmail.com');
INSERT INTO APP_USERS(USER_ID,EMAIL) VALUES (USER_ID_SEQ.NEXTVAL,'pooji@gmail.com');
INSERT INTO APP_USERS(USER_ID,EMAIL) VALUES (USER_ID_SEQ.NEXTVAL,'poojitha@gmail.com');
INSERT INTO APP_USERS(USER_ID,EMAIL) VALUES (USER_ID_SEQ.NEXTVAL,'uncle@gmail.com');


INSERT INTO APP_TASKS(USER_ID, TASK_NAME, DESCRIPTION, STATUS, DUE_DATE,CATEGORY, CREATE_DATE, UPDATED_DATE) VALUES (1, 'Complete Web Development Project', 'Build a TODO list tracker with frontend and backend functionality.', 'PENDING', TO_DATE('2024-02-10', 'YYYY-MM-DD'),'family', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO APP_TASKS(USER_ID, TASK_NAME, DESCRIPTION, STATUS, DUE_DATE,CATEGORY, CREATE_DATE, UPDATED_DATE) VALUES(2, 'Complete Web Development Project', 'Build a TODO list tracker with frontend and backend functionality.', 'PENDING', TO_DATE('2024-01-14', 'YYYY-MM-DD'), 'work',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO APP_TASKS(USER_ID, TASK_NAME, DESCRIPTION, STATUS, DUE_DATE,CATEGORY, CREATE_DATE, UPDATED_DATE) VALUES(3, 'Complete Web Development Project', 'Build a TODO list tracker with frontend and backend functionality.', 'COMPLETE', TO_DATE('2023-06-20', 'YYYY-MM-DD'), 'personal',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO APP_TASKS(USER_ID, TASK_NAME, DESCRIPTION, STATUS, DUE_DATE,CATEGORY, CREATE_DATE, UPDATED_DATE) VALUES(4, 'Complete Web Development Project', 'Build a TODO list tracker with frontend and backend functionality.', 'PENDING', TO_DATE('2022-09-15', 'YYYY-MM-DD'), 'family',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO APP_TASKS(USER_ID, TASK_NAME, DESCRIPTION, STATUS, DUE_DATE, CATEGORY,CREATE_DATE, UPDATED_DATE) VALUES(5, 'Complete Web Development Project', 'Build a TODO list tracker with frontend and backend functionality.', 'COMPLETE', TO_DATE('2024-07-25', 'YYYY-MM-DD'),'work', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO APP_TASKS(USER_ID, TASK_NAME, DESCRIPTION, STATUS, DUE_DATE, CATEGORY,CREATE_DATE, UPDATED_DATE) VALUES(6, 'Complete Web Development Project', 'Build a TODO list tracker with frontend and backend functionality.', 'COMPLETE', TO_DATE('2024-04-29', 'YYYY-MM-DD'),'myself', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO APP_TASKS(USER_ID, TASK_NAME, DESCRIPTION, STATUS, DUE_DATE, CATEGORY,CREATE_DATE, UPDATED_DATE) VALUES(7, 'Complete Web Development Project', 'Build a TODO list tracker with frontend and backend functionality.', 'PENDING', TO_DATE('2024-12-11', 'YYYY-MM-DD'),'family', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);





